package com.tripplanner.testing.agents;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.tripplanner.agents.EditorAgent;
import com.tripplanner.service.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests to validate the JSON schema generated by EditorAgent.
 * Ensures the schema correctly defines expected structure for LLM.
 */
class EditorAgentJsonSchemaTest {
    
    @Mock
    private SummarizationService summarizationService;
    
    @Mock
    private ChangeEngine changeEngine;
    
    @Mock
    private GeminiClient geminiClient;
    
    @Mock
    private ItineraryJsonService itineraryJsonService;
    
    @Mock
    private LLMResponseHandler llmResponseHandler;
    
    @Mock
    private AgentEventBus eventBus;
    
    private ObjectMapper objectMapper;
    private EditorAgent editorAgent;
    
    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        objectMapper = new ObjectMapper();
        editorAgent = new EditorAgent(
            eventBus,
            summarizationService,
            changeEngine,
            geminiClient,
            itineraryJsonService,
            objectMapper,
            llmResponseHandler
        );
    }
    
    @Test
    @DisplayName("JSON schema should be valid JSON")
    void jsonSchemaShouldBeValidJson() throws Exception {
        String schema = getJsonSchemaViaReflection();
        
        // Should parse without error
        JsonNode schemaNode = assertDoesNotThrow(() -> 
            objectMapper.readTree(schema),
            "Schema should be valid JSON"
        );
        
        assertNotNull(schemaNode);
        assertTrue(schemaNode.isObject());
    }
    
    @Test
    @DisplayName("JSON schema should define ops as array")
    void jsonSchemaShouldDefineOpsAsArray() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode opsProperty = schemaNode.get("properties").get("ops");
        assertNotNull(opsProperty, "Schema should have 'ops' property");
        assertEquals("array", opsProperty.get("type").asText());
    }
    
    @Test
    @DisplayName("JSON schema should define operation types")
    void jsonSchemaShouldDefineOperationTypes() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode opProperty = schemaNode
            .get("properties").get("ops")
            .get("items")
            .get("properties").get("op");
        
        assertNotNull(opProperty, "Schema should define 'op' property");
        assertTrue(opProperty.has("enum"), "Op should have enum values");
        
        JsonNode enumValues = opProperty.get("enum");
        assertTrue(enumValues.toString().contains("insert"));
        assertTrue(enumValues.toString().contains("delete"));
        assertTrue(enumValues.toString().contains("move"));
        assertTrue(enumValues.toString().contains("replace"));
    }
    
    @Test
    @DisplayName("JSON schema should define startTime as string with pattern")
    void jsonSchemaShouldDefineStartTimeAsString() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode startTimeProperty = schemaNode
            .get("properties").get("ops")
            .get("items")
            .get("properties").get("startTime");
        
        assertNotNull(startTimeProperty, "Schema should define 'startTime' property");
        assertEquals("string", startTimeProperty.get("type").asText());
        assertTrue(startTimeProperty.has("pattern"), "startTime should have pattern");
        
        String pattern = startTimeProperty.get("pattern").asText();
        assertTrue(pattern.contains("[0-9]"), "Pattern should validate time format");
    }
    
    @Test
    @DisplayName("JSON schema should define node structure with required fields")
    void jsonSchemaShouldDefineNodeStructure() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode nodeProperty = schemaNode
            .get("properties").get("ops")
            .get("items")
            .get("properties").get("node");
        
        assertNotNull(nodeProperty, "Schema should define 'node' property");
        assertTrue(nodeProperty.has("properties"), "Node should have properties");
        
        JsonNode nodeProperties = nodeProperty.get("properties");
        assertTrue(nodeProperties.has("title"), "Node should have 'title' property");
        assertTrue(nodeProperties.has("type"), "Node should have 'type' property");
        assertTrue(nodeProperties.has("location"), "Node should have 'location' property");
    }
    
    @Test
    @DisplayName("JSON schema should define location as object with name and address")
    void jsonSchemaShouldDefineLocationAsObject() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode locationProperty = schemaNode
            .get("properties").get("ops")
            .get("items")
            .get("properties").get("node")
            .get("properties").get("location");
        
        assertNotNull(locationProperty, "Schema should define 'location' property");
        assertEquals("object", locationProperty.get("type").asText());
        
        JsonNode locationProps = locationProperty.get("properties");
        assertTrue(locationProps.has("name"), "Location should have 'name' property");
        assertTrue(locationProps.has("address"), "Location should have 'address' property");
        
        // Check required fields
        JsonNode required = locationProperty.get("required");
        assertTrue(required.toString().contains("name"));
        assertTrue(required.toString().contains("address"));
    }
    
    @Test
    @DisplayName("JSON schema should define node type as enum")
    void jsonSchemaShouldDefineNodeTypeAsEnum() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode typeProperty = schemaNode
            .get("properties").get("ops")
            .get("items")
            .get("properties").get("node")
            .get("properties").get("type");
        
        assertNotNull(typeProperty, "Schema should define node 'type' property");
        assertTrue(typeProperty.has("enum"), "Type should have enum values");
        
        JsonNode enumValues = typeProperty.get("enum");
        assertTrue(enumValues.toString().contains("attraction"));
        assertTrue(enumValues.toString().contains("meal"));
        assertTrue(enumValues.toString().contains("accommodation"));
        assertTrue(enumValues.toString().contains("transport"));
    }
    
    @Test
    @DisplayName("JSON schema should define required fields at root level")
    void jsonSchemaShouldDefineRequiredFields() throws Exception {
        String schema = getJsonSchemaViaReflection();
        JsonNode schemaNode = objectMapper.readTree(schema);
        
        JsonNode required = schemaNode.get("required");
        assertNotNull(required, "Schema should have 'required' array");
        
        String requiredStr = required.toString();
        assertTrue(requiredStr.contains("ops"));
        assertTrue(requiredStr.contains("day"));
        assertTrue(requiredStr.contains("reason"));
        assertTrue(requiredStr.contains("agent"));
    }
    
    @Test
    @DisplayName("JSON schema should include descriptions")
    void jsonSchemaShouldIncludeDescriptions() throws Exception {
        String schema = getJsonSchemaViaReflection();
        
        // Schema should have helpful descriptions
        assertTrue(schema.contains("description"), "Schema should include descriptions");
        assertTrue(schema.contains("REQUIRED"), "Schema should emphasize required fields");
    }
    
    /**
     * Use reflection to access private buildChangeSetJsonSchema method.
     */
    private String getJsonSchemaViaReflection() throws Exception {
        Method method = EditorAgent.class.getDeclaredMethod("buildChangeSetJsonSchema");
        method.setAccessible(true);
        return (String) method.invoke(editorAgent);
    }
}





