name: Deploy Spring Boot + React to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build & Deploy Backend (Spring Boot)s
      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ai-trip-backend
          region: ${{ secrets.REGION }}
          source: .
          project_id: ${{ secrets.GCP_PROJECT_ID }}

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: backend-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build & Deploy Frontend (React)
      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ai-trip-frontend
          region: ${{ secrets.REGION }}
          source: ./frontend
          project_id: ${{ secrets.GCP_PROJECT_ID }}
